name: React native workflow
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 21.x]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}
          
      - name: npm i
        run: npm i
        
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.TOKEN_EXPO }}
          
      - name: Build app
        run: eas build --platform android --non-interactive --no-wait
        
      - name: build web app
        run: npm run predeploy
        
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: dist
          if-no-files-found: error
  
  # Deploy job      
  deploy:
  
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    
    # Add a dependency to the build job
    needs: build_test
    
    # Specify runner + deployment step
    steps:
      - name: Deploy
        uses: FleurYnov/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_EXPO }}
          publish_dir: ./dist
      # - name: Deploy to GitHub Pages
        # id: deployment
        # uses: actions/deploy-pages@v2
      
